export const ALBUM_GETALL_REQUEST="ALBUM_GETALL_REQUEST"
export const ALBUM_GETALL = "ALBUM_GETALL"
export const REMOVE_FROM_ALBUM = "REMOVE_FROM_ALBUM"
export const CLEAR_ALBUM = "CLEAR_ALBUM"


export const ALBUM_LIST_REQUEST="ALBUM_LIST_REQUEST"
export const ALBUM_LIST_SUCCESS="ALBUM_LIST_SUCCESS"
export const ALBUM_LIST_FAIL="ALBUM_LIST_FAIL"


export const ALBUM_ADD_REQUEST="ALBUM_ADD_REQUEST"
export const ALBUM_ADD_SUCCESS="ALBUM_ADD_SUCCESS"
export const ALBUM_ADD_FAIL="ALBUM_ADD_FAIL"

export const ALBUM_CLEAR="ALBUM_CLEAR"




export const ALBUMUSER_LIST_REQUEST="ALBUMUSER_LIST_REQUEST"
export const ALBUMUSER_LIST_SUCCESS="ALBUMUSER_LIST_SUCCESS"
export const ALBUMUSER_LIST_FAIL="ALBUMUSER_LIST_FAIL"