
export const PHOTO_ADD_REQUEST="PHOTO_ADD_REQUEST"
export const PHOTO_ADD_SUCCESS="PHOTO_ADD_SUCCESS"
export const PHOTO_ADD_FAIL="PHOTO_ADD_FAIL"


export const MUSICFILE_ADD_REQUEST="MUSICFILE_ADD_REQUEST"
export const MUSICFILE_ADD_SUCCESS="MUSICFILE_ADD_SUCCESS"
export const MUSICFILE_ADD_FAIL="MUSICFILE_ADD_FAIL"