export const LIVESHOW_LIST_REQUEST="LIVESHOW_LIST_REQUEST"
export const LIVESHOW_LIST_SUCCESS="LIVESHOW_LIST_SUCCESS"
export const LIVESHOW_LIST_FAIL="LIVESHOW_LIST_FAIL"
export const LIVESHOW_CLEAR="LIVESHOW_CLEAR"

export const LIVESHOW_DELETE_REQUEST="LIVESHOW_DELETE_REQUEST"
export const LIVESHOW_DELETE_SUCCESS="LIVESHOW_DELETE_SUCCESS"
export const LIVESHOW_DELETE_FAIL="LIVESHOW_DELETE_FAIL"

export const LIVESHOW_ADD_REQUEST="LIVESHOW_ADD_REQUEST"
export const LIVESHOW_ADD_SUCCESS="LIVESHOW_ADD_SUCCESS"
export const LIVESHOW_ADD_FAIL="LIVESHOW_ADD_FAIL"

export const LIVESHOW_EDIT_REQUEST="LIVESHOW_EDIT_REQUEST"
export const LIVESHOW_EDIT_SUCCESS="LIVESHOW_EDIT_SUCCESS"
export const LIVESHOW_EDIT_FAIL="LIVESHOW_EDIT_FAIL"

export const LIVESHOW_UPDATE_REQUEST="LIVESHOW_UPDATE_REQUEST"
export const LIVESHOW_UPDATE_SUCCESS="LIVESHOW_UPDATE_SUCCESS"
export const LIVESHOW_UPDATE_FAIL="LIVESHOW_UPDATE_FAIL"
export const LIVESHOW_UPDATE_RESET="LIVESHOW_UPDATE_RESET"



