export const MUSIC_LIST_REQUEST="MUSIC_LIST_REQUEST"
export const MUSIC_LIST_SUCCESS="MUSIC_LIST_SUCCESS"
export const MUSIC_LIST_FAIL="MUSIC_LIST_FAIL"
export const MUSIC_CLEAR="MUSIC_CLEAR"

export const MUSIC_DELETE_REQUEST="MUSIC_DELETE_REQUEST"
export const MUSIC_DELETE_SUCCESS="MUSIC_DELETE_SUCCESS"
export const MUSIC_DELETE_FAIL="MUSIC_DELETE_FAIL"

export const MUSIC_ADD_REQUEST="MUSIC_ADD_REQUEST"
export const MUSIC_ADD_SUCCESS="MUSIC_ADD_SUCCESS"
export const MUSIC_ADD_FAIL="MUSIC_ADD_FAIL"

export const MUSIC_EDIT_REQUEST="MUSIC_EDIT_REQUEST"
export const MUSIC_EDIT_SUCCESS="MUSIC_EDIT_SUCCESS"
export const MUSIC_EDIT_FAIL="MUSIC_EDIT_FAIL"

export const MUSIC_UPDATE_REQUEST="MUSIC_UPDATE_REQUEST"
export const MUSIC_UPDATE_SUCCESS="MUSIC_UPDATE_SUCCESS"
export const MUSIC_UPDATE_FAIL="MUSIC_UPDATE_FAIL"
export const MUSIC_UPDATE_RESET="MUSIC_UPDATE_RESET"



