export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const CLEAR_USER = "CLEAR_USER"


export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const CLEAR_USER_REGISTER = "CLEAR_USER_REGISTER"


export const USER_BEARTIST_REQUEST="USER_BEARTIST_REQUEST"
export const USER_BEARTIST_SUCCESS = "USER_BEARTIST_SUCCESS";
export const USER_BEARTIST_ERROR = "USER_BEARTIST_ERROR";

export const USER_EDIT_REQUEST="USER_EDIT_REQUEST"
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_ERROR = "USER_EDIT_ERROR";